---
name: "Deploy to Cloud Run"
description: "Deploys a container image to Google Cloud Run."

inputs:
  gcp_project_id:
    description: "GCP Project ID"
    required: true
  service_name:
    description: "Cloud Run Service Name"
    required: true
  region:
    description: "GCP Region"
    required: true
    default: "us-central1"
  image_url:
    description: "The full URL of the Docker image to deploy"
    required: true
  allow_unauthenticated:
    description: "Whether to allow unauthenticated access (true/false)"
    required: false
    default: "true"

runs:
  using: "composite"
  steps:
    - name: Authenticate with GCP
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Ensure `entrypoint.sh` is executable
      run: chmod +x ${{ github.action_path }}/entrypoint.sh
      shell: bash

    - name: Deploy to Cloud Run
      shell: bash
      env:
        GCP_PROJECT_ID: ${{ inputs.gcp_project_id }}
        SERVICE_NAME: ${{ inputs.service_name }}
        REGION: ${{ inputs.region }}
        IMAGE_URL: ${{ inputs.image_url }}
        ALLOW_UNAUTHENTICATED: ${{ inputs.allow_unauthenticated }}
      run: ${{ github.action_path }}/entrypoint.sh
