---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: debug-statements

  # YAML Linter
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.35.1
    hooks:
      - id: yamllint
        args: ["-c", ".yamllint"]

  # Ruff for formatting and linting (replacing Black, Isort, Pylint)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.6
    hooks:
      - id: ruff
        args:
          - --fix
      - id: ruff-format

  # Mypy for static type checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy
        additional_dependencies:
          - pandas-stubs
          - types-requests
          - types-pyyaml
          - types-setuptools
          - types-toml

  # Bandit for security scans (excluding tests/)
  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.3
    hooks:
      - id: bandit
        args:
          - "-r"
          - "."
          - "--exclude"
          - "tests,venv,.venv"
        pass_filenames: false
