---
version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: daily
    allow:
      - dependency-type: "direct"
    ignore:
      - dependency-name: "poetry"  # Since we're moving to uv
    groups:
      all:
        patterns:
          - "*"

    reviewers:
      # Reviewers list
      - EQB3823_hca  # Dan
      - QXA3488_hca  # Matthew
      - HGE3226_hca  # Ashwin
      - FZA3347_hca  # Chaithanya

    assignees:
      - FZA3347_hca  # Chaithanya

    labels:
      - "dependencies"
      - "automated update"

    commit-message:
      prefix: "[Dependabot]"
      include: "scope"

    open-pull-requests-limit: 10

    # Automatically rebase if conflicts occur
    rebase-strategy: auto

    # Prefer updates to the next minor/patch version
    versioning-strategy: increase
